services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: